basePath: /todos
definitions:
  models.Todo:
    properties:
      completed:
        type: boolean
      id:
        type: integer
      name:
        type: string
    required:
    - id
    - name
    type: object
host: localhost:8080
info:
  contact:
    email: amadijerry823@gmail.com
    name: Amadi Jerry
    url: https://twitter.com/Jerry_Jaeger_
  description: A TODO APP API in Go using Gin framework.
  title: Todo App API
  version: "1.0"
paths:
  /:
    get:
      description: Responds with the list of all Todos as JSON.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Todo'
            type: array
      summary: Get Todos array
      tags:
      - todos
swagger: "2.0"
